// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJE3FXZFEwUWxu8PFYs5VHfEmEFOx05yk',
    appId: '1:885406184922:web:56938530cf79ca09c83ce3',
    messagingSenderId: '885406184922',
    projectId: 'ghanayouthparliament-a1597',
    authDomain: 'ghanayouthparliament-a1597.firebaseapp.com',
    storageBucket: 'ghanayouthparliament-a1597.appspot.com',
    measurementId: 'G-V1LM97PE6F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS2IrBpO2jtjfXpwA8s27UBu7ZMJRyLhY',
    appId: '1:885406184922:android:a6c0e20364c4a881c83ce3',
    messagingSenderId: '885406184922',
    projectId: 'ghanayouthparliament-a1597',
    storageBucket: 'ghanayouthparliament-a1597.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmU4UC3oSPeGqubUa3nzTTzeODDIYIR0c',
    appId: '1:885406184922:ios:790e60c7422baf1bc83ce3',
    messagingSenderId: '885406184922',
    projectId: 'ghanayouthparliament-a1597',
    storageBucket: 'ghanayouthparliament-a1597.appspot.com',
    iosBundleId: 'com.ghanayouth.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmU4UC3oSPeGqubUa3nzTTzeODDIYIR0c',
    appId: '1:885406184922:ios:a9e87b3f25183a6ec83ce3',
    messagingSenderId: '885406184922',
    projectId: 'ghanayouthparliament-a1597',
    storageBucket: 'ghanayouthparliament-a1597.appspot.com',
    iosBundleId: 'com.example.ecg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJE3FXZFEwUWxu8PFYs5VHfEmEFOx05yk',
    appId: '1:885406184922:web:e84161f2b5864774c83ce3',
    messagingSenderId: '885406184922',
    projectId: 'ghanayouthparliament-a1597',
    authDomain: 'ghanayouthparliament-a1597.firebaseapp.com',
    storageBucket: 'ghanayouthparliament-a1597.appspot.com',
    measurementId: 'G-W96BQC4QR0',
  );
}
