// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdeBLVVDhg5OZ7azG0eLRMirLDnr97uB4',
    appId: '1:383281681009:web:223c969c86623ac1f9c1d0',
    messagingSenderId: '383281681009',
    projectId: 'ylpapp-66bd6',
    authDomain: 'ylpapp-66bd6.firebaseapp.com',
    storageBucket: 'ylpapp-66bd6.appspot.com',
    measurementId: 'G-VCZMFFW97Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyaCHxskmo8-6KYTxVEOIir2wxg5RIMoM',
    appId: '1:383281681009:android:a71ecd4b86ceeec6f9c1d0',
    messagingSenderId: '383281681009',
    projectId: 'ylpapp-66bd6',
    storageBucket: 'ylpapp-66bd6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy_be63IQrEf2Ndp7Hd38zEZSbL-ZpUcw',
    appId: '1:383281681009:ios:edb8288746a2d838f9c1d0',
    messagingSenderId: '383281681009',
    projectId: 'ylpapp-66bd6',
    storageBucket: 'ylpapp-66bd6.appspot.com',
    androidClientId: '383281681009-86h4cktof43hh84g0kj1o9ki7bjuk8gc.apps.googleusercontent.com',
    iosClientId: '383281681009-inncpo7s5a7g57bdiv6h0f0937lv5kkc.apps.googleusercontent.com',
    iosBundleId: 'com.ghanayouth.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDy_be63IQrEf2Ndp7Hd38zEZSbL-ZpUcw',
    appId: '1:383281681009:ios:68e027b8930d1e0bf9c1d0',
    messagingSenderId: '383281681009',
    projectId: 'ylpapp-66bd6',
    storageBucket: 'ylpapp-66bd6.appspot.com',
    androidClientId: '383281681009-86h4cktof43hh84g0kj1o9ki7bjuk8gc.apps.googleusercontent.com',
    iosClientId: '383281681009-qo1c055e45vfv7s4end9o34ttae2o0kk.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdeBLVVDhg5OZ7azG0eLRMirLDnr97uB4',
    appId: '1:383281681009:web:922042ac072aa513f9c1d0',
    messagingSenderId: '383281681009',
    projectId: 'ylpapp-66bd6',
    authDomain: 'ylpapp-66bd6.firebaseapp.com',
    storageBucket: 'ylpapp-66bd6.appspot.com',
    measurementId: 'G-1FSW5YDMSV',
  );
}